import type { AppLocale } from '@/locales/locale';

export const DEFAULT_CATEGORIES: Record<AppLocale, readonly { name: string; color: string }[]> = {
  en: [
    { name: 'Housing', color: '#4A90E2' },
    { name: 'Food', color: '#F5A623' },
    { name: 'Transportation', color: '#7B61FF' },
    { name: 'Health', color: '#E94B5F' },
    { name: 'Education', color: '#2D9CDB' },
    { name: 'Shopping', color: '#BB6BD9' },
    { name: 'Leisure', color: '#F2994A' },
    { name: 'Travel', color: '#00A6A6' },
    { name: 'Subscriptions', color: '#6366F1' },
    { name: 'Services', color: '#607D8B' },
    { name: 'Taxes and fees', color: '#8D6E63' },
    { name: 'Financial', color: '#455A64' },
    { name: 'Investments', color: '#27AE60' },
    { name: 'Family', color: '#EC407A' },
    { name: 'Pets', color: '#A1887F' },
    { name: 'Work', color: '#546E7A' },
    { name: 'Other', color: '#9E9E9E' },
  ],
  'pt-BR': [
    { name: 'Moradia', color: '#4A90E2' },
    { name: 'Alimentação', color: '#F5A623' },
    { name: 'Transporte', color: '#7B61FF' },
    { name: 'Saúde', color: '#E94B5F' },
    { name: 'Educação', color: '#2D9CDB' },
    { name: 'Compras', color: '#BB6BD9' },
    { name: 'Lazer', color: '#F2994A' },
    { name: 'Viagens', color: '#00A6A6' },
    { name: 'Assinaturas', color: '#6366F1' },
    { name: 'Serviços', color: '#607D8B' },
    { name: 'Impostos e taxas', color: '#8D6E63' },
    { name: 'Financeiro', color: '#455A64' },
    { name: 'Investimentos', color: '#27AE60' },
    { name: 'Família', color: '#EC407A' },
    { name: 'Pets', color: '#A1887F' },
    { name: 'Trabalho', color: '#546E7A' },
    { name: 'Outros', color: '#9E9E9E' },
  ],
};
