import type { AppLocale } from '@/locales/locale';

export const DEFAULT_TAGS: Record<AppLocale, readonly { name: string; color: string }[]> = {
  en: [
    { name: 'Groceries', color: '#66BB6A' },
    { name: 'Restaurant', color: '#FF7043' },
    { name: 'Delivery', color: '#EF5350' },
    { name: 'Snacks', color: '#FFA726' },
    { name: 'Bakery', color: '#FFCA28' },
    { name: 'Fuel', color: '#3949AB' },
    { name: 'Uber', color: '#43A047' },
    { name: 'Public transport', color: '#1E88E5' },
    { name: 'Parking', color: '#546E7A' },
    { name: 'Maintenance', color: '#78909C' },
    { name: 'Insurance', color: '#5E35B1' },
    { name: 'Pharmacy', color: '#EF5350' },
    { name: 'Doctor visit', color: '#EC407A' },
    { name: 'Medical test', color: '#AB47BC' },
    { name: 'Dentist', color: '#7E57C2' },
    { name: 'Gym', color: '#26A69A' },
    { name: 'Course', color: '#42A5F5' },
    { name: 'Books', color: '#5C6BC0' },
    { name: 'Clothing', color: '#EC407A' },
    { name: 'Electronics', color: '#5C6BC0' },
    { name: 'Computer', color: '#3949AB' },
    { name: 'Movies', color: '#7E57C2' },
    { name: 'Games', color: '#5E35B1' },
    { name: 'Concerts', color: '#EC407A' },
    { name: 'Streaming', color: '#E53935' },
    { name: 'Airfare', color: '#29B6F6' },
    { name: 'Lodging', color: '#42A5F5' },
    { name: 'Credit card', color: '#455A64' },
    { name: 'Bank fee', color: '#607D8B' },
    { name: 'Interest', color: '#E53935' },
    { name: 'Loan', color: '#8D6E63' },
    { name: 'Financing', color: '#795548' },
    { name: 'Contribution', color: '#2E7D32' },
    { name: 'Fixed income', color: '#43A047' },
    { name: 'Stocks', color: '#1565C0' },
    { name: 'Funds', color: '#5E35B1' },
    { name: 'Crypto', color: '#F9A825' },
    { name: 'Dividends', color: '#00897B' },
    { name: 'Work', color: '#1565C0' },
    { name: 'Family', color: '#EC407A' },
    { name: 'Emergency', color: '#D32F2F' },
    { name: 'Essential', color: '#43A047' },
    { name: 'Want', color: '#FB8C00' },
    { name: 'Recurring', color: '#5C6BC0' },
    { name: 'Installments', color: '#8E24AA' },
    { name: 'Refund', color: '#00ACC1' },
    { name: 'Trip', color: '#29B6F6' },
    { name: 'Uber Eats', color: '#38AB1B' },
  ],
  'pt-BR': [
    { name: 'Supermercado', color: '#66BB6A' },
    { name: 'Restaurante', color: '#FF7043' },
    { name: 'Delivery', color: '#EF5350' },
    { name: 'Lanches', color: '#FFA726' },
    { name: 'Padaria', color: '#FFCA28' },
    { name: 'Combustível', color: '#3949AB' },
    { name: 'Uber', color: '#43A047' },
    { name: 'Transporte público', color: '#1E88E5' },
    { name: 'Estacionamento', color: '#546E7A' },
    { name: 'Manutenção', color: '#78909C' },
    { name: 'Seguro', color: '#5E35B1' },
    { name: 'Farmácia', color: '#EF5350' },
    { name: 'Consulta', color: '#EC407A' },
    { name: 'Exame', color: '#AB47BC' },
    { name: 'Dentista', color: '#7E57C2' },
    { name: 'Academia', color: '#26A69A' },
    { name: 'Curso', color: '#42A5F5' },
    { name: 'Livro', color: '#5C6BC0' },
    { name: 'Roupas', color: '#EC407A' },
    { name: 'Eletrônicos', color: '#5C6BC0' },
    { name: 'Computador', color: '#3949AB' },
    { name: 'Cinema', color: '#7E57C2' },
    { name: 'Jogos', color: '#5E35B1' },
    { name: 'Shows', color: '#EC407A' },
    { name: 'Streaming', color: '#E53935' },
    { name: 'Passagem', color: '#29B6F6' },
    { name: 'Hospedagem', color: '#42A5F5' },
    { name: 'Cartão de crédito', color: '#455A64' },
    { name: 'Tarifa bancária', color: '#607D8B' },
    { name: 'Juros', color: '#E53935' },
    { name: 'Empréstimo', color: '#8D6E63' },
    { name: 'Financiamento', color: '#795548' },
    { name: 'Aporte', color: '#2E7D32' },
    { name: 'Renda fixa', color: '#43A047' },
    { name: 'Ações', color: '#1565C0' },
    { name: 'Fundos', color: '#5E35B1' },
    { name: 'Criptomoedas', color: '#F9A825' },
    { name: 'Dividendos', color: '#00897B' },
    { name: 'Trabalho', color: '#1565C0' },
    { name: 'Família', color: '#EC407A' },
    { name: 'Emergência', color: '#D32F2F' },
    { name: 'Necessário', color: '#43A047' },
    { name: 'Desejo', color: '#FB8C00' },
    { name: 'Recorrente', color: '#5C6BC0' },
    { name: 'Parcelado', color: '#8E24AA' },
    { name: 'Reembolso', color: '#00ACC1' },
    { name: 'Viagem', color: '#29B6F6' },
    { name: 'iFood', color: '#C20C27' },
    { name: 'Uber Eats', color: '#38AB1B' },
    { name: '99Food', color: '#EDE60E' },
    { name: '99Taxi', color: '#EDE60E' },
    { name: 'Zé Delivery', color: '#D6D131' },
  ],
};
